env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
rules:
  no-inner-declarations: off
  indent:
    - error
    - 2
    - SwitchCase: 1
  '@typescript-eslint/no-explicit-any': off

parserOptions:
  ecmaVersion: 2018
  sourceType: module
