/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var wrappers_pb = require('./wrappers_pb.js');
var uint128_pb = require('./uint128_pb.js');
goog.exportSymbol('proto.AccessKey', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.AccessKey = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.AccessKey, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.AccessKey.displayName = 'proto.AccessKey';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.AccessKey.prototype.toObject = function(opt_includeInstance) {
  return proto.AccessKey.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.AccessKey} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AccessKey.toObject = function(includeInstance, msg) {
  var f, obj = {
    amount: (f = msg.getAmount()) && uint128_pb.Uint128.toObject(includeInstance, f),
    balanceOwner: (f = msg.getBalanceOwner()) && wrappers_pb.StringValue.toObject(includeInstance, f),
    contractId: (f = msg.getContractId()) && wrappers_pb.StringValue.toObject(includeInstance, f),
    methodName: (f = msg.getMethodName()) && wrappers_pb.BytesValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.AccessKey}
 */
proto.AccessKey.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.AccessKey;
  return proto.AccessKey.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.AccessKey} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.AccessKey}
 */
proto.AccessKey.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new uint128_pb.Uint128;
      reader.readMessage(value,uint128_pb.Uint128.deserializeBinaryFromReader);
      msg.setAmount(value);
      break;
    case 2:
      var value = new wrappers_pb.StringValue;
      reader.readMessage(value,wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setBalanceOwner(value);
      break;
    case 3:
      var value = new wrappers_pb.StringValue;
      reader.readMessage(value,wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setContractId(value);
      break;
    case 4:
      var value = new wrappers_pb.BytesValue;
      reader.readMessage(value,wrappers_pb.BytesValue.deserializeBinaryFromReader);
      msg.setMethodName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.AccessKey.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.AccessKey.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.AccessKey} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AccessKey.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAmount();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      uint128_pb.Uint128.serializeBinaryToWriter
    );
  }
  f = message.getBalanceOwner();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getContractId();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getMethodName();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      wrappers_pb.BytesValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional Uint128 amount = 1;
 * @return {?proto.Uint128}
 */
proto.AccessKey.prototype.getAmount = function() {
  return /** @type{?proto.Uint128} */ (
    jspb.Message.getWrapperField(this, uint128_pb.Uint128, 1));
};


/** @param {?proto.Uint128|undefined} value */
proto.AccessKey.prototype.setAmount = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.AccessKey.prototype.clearAmount = function() {
  this.setAmount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.AccessKey.prototype.hasAmount = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.StringValue balance_owner = 2;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.AccessKey.prototype.getBalanceOwner = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, wrappers_pb.StringValue, 2));
};


/** @param {?proto.google.protobuf.StringValue|undefined} value */
proto.AccessKey.prototype.setBalanceOwner = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.AccessKey.prototype.clearBalanceOwner = function() {
  this.setBalanceOwner(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.AccessKey.prototype.hasBalanceOwner = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.StringValue contract_id = 3;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.AccessKey.prototype.getContractId = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, wrappers_pb.StringValue, 3));
};


/** @param {?proto.google.protobuf.StringValue|undefined} value */
proto.AccessKey.prototype.setContractId = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.AccessKey.prototype.clearContractId = function() {
  this.setContractId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.AccessKey.prototype.hasContractId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.BytesValue method_name = 4;
 * @return {?proto.google.protobuf.BytesValue}
 */
proto.AccessKey.prototype.getMethodName = function() {
  return /** @type{?proto.google.protobuf.BytesValue} */ (
    jspb.Message.getWrapperField(this, wrappers_pb.BytesValue, 4));
};


/** @param {?proto.google.protobuf.BytesValue|undefined} value */
proto.AccessKey.prototype.setMethodName = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.AccessKey.prototype.clearMethodName = function() {
  this.setMethodName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.AccessKey.prototype.hasMethodName = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto);
