'use strict';
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
const providers = __importStar(require("./providers"));
exports.providers = providers;
const utils = __importStar(require("./utils"));
exports.utils = utils;
const keyStores = __importStar(require("./key_stores/browser-index"));
exports.keyStores = keyStores;
const transactions = __importStar(require("./transaction"));
exports.transactions = transactions;
const account_1 = require("./account");
exports.Account = account_1.Account;
const accountCreator = __importStar(require("./account_creator"));
exports.accountCreator = accountCreator;
const connection_1 = require("./connection");
exports.Connection = connection_1.Connection;
const signer_1 = require("./signer");
exports.Signer = signer_1.Signer;
exports.InMemorySigner = signer_1.InMemorySigner;
const contract_1 = require("./contract");
exports.Contract = contract_1.Contract;
const key_pair_1 = require("./utils/key_pair");
exports.KeyPair = key_pair_1.KeyPair;
const near_1 = require("./near");
exports.connect = near_1.connect;
// TODO: Deprecate and remove WalletAccount
const wallet_account_1 = require("./wallet-account");
exports.WalletAccount = wallet_account_1.WalletAccount;
exports.WalletConnection = wallet_account_1.WalletConnection;
