name: Docs Generator trigger

on:
  workflow_run:
    workflows: [Release]
    types: [completed]
    branches: [master]

concurrency:
  group: "docs"
  cancel-in-progress: true

jobs:
  trigger-generator:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: DOCS
    steps:
    - name: Trigger generator
      run: |
        curl -i -v --location --request POST 'https://docs-bot.vercel.app/api/on-release' \
        --header 'bot-auth: ${{ secrets.DOCS_BOT_SECRET }}' \
        --header 'Content-Type: application/json' \
        --data-raw '{
          "event_type": "release-publish",
          "client_payload": {
            "source_repo": "near/near-api-js",
            "builder_name": "near-api-js",
            "release_version": "${{ github.ref_name }}"
          }
        }'