name: Pull Request Title Lint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

jobs:
  lint-pr-title:
    name: "Lint PR title for Conventional Commits"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'merge_group'
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            docs
            style
            refactor
            perf
            test
            build
            ci
            revert
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 